---
- name: Save and Backup the configuration
  hosts: [leaf, bleaf, spine]
  connection: local
  gather_facts: no
  strategy: free

  roles:
    - common

  vars:
    playbook_name: "Save and backup the configuration"

  tasks:
    - block:
        - name: "Save the configuration"
          nxos_config:
            lines: copy running-config startup-config
            provider: "{{ nxapi }}"
          tags:
            - save
        - name: "Create checkpoint"
          nxos_rollback:
            checkpoint_file: backup.cfg
            provider: "{{ nxapi }}"
          tags:
            - checkpoint
        - name: "Backup the configuration"
          nxos_config:
            backup: yes
            provider: "{{ nxapi }}"
          tags:
            - backup
      rescue:
        - set_fact:
            trigger_msg: True
            send_msg: "{{ playbook_name }} -  error configure on {{ inventory_hostname }}"
          changed_when: True
          notify: notify using spark
...
